name: Create tar.gz on tag

on:
  push:
    tags:
      - '*'

jobs:
  build-archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create tar.gz
        run: |
          mkdir -p dist
          git archive --format=tar.gz --prefix=${{ github.repository }}/ ${{ github.ref_name }} > dist/${{ github.ref_name }}.tar.gz

      - name: Upload archive to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/${{ github.ref_name }}.tar.gz
